# Optional: Nginx Reverse Proxy with Docker
# This is an alternative to installing Nginx directly on the host
# Use this if you want everything containerized

version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: blue-escape-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    networks:
      - blue-escape-network
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    container_name: blue-escape-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  blue-escape-network:
    external: true

