-- Seed admin user for Blue Escape Backend
-- Username: admin
-- Password: luxurytravelmadeeasy
-- This script inserts the default admin user if it doesn't exist

USE blue_escape_db;

-- Insert admin user
-- Password: luxurytravelmadeeasy (bcrypt hashed with 10 rounds)
INSERT INTO users (id, username, password, active, created_at, updated_at)
SELECT
    UUID(),
    'admin',
    '$2b$10$xYz9P3Q7K8mN5vL2wR4tJ.iF6gH7jK8lM9nO0pQ1rS2tU3vW4xY5z', -- This is a placeholder, actual hash will be generated by NestJS
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 FROM users WHERE username = 'admin'
);

-- Note: The password hash above is a placeholder format.
-- The actual admin user will be created automatically by NestJS on first run
-- if it doesn't exist. This is handled by the AuthService.
